-- MySQL Script generated by MySQL Workbench
-- sex 15 jun 2018 23:15:03 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema creditos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema creditos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `creditos` DEFAULT CHARACTER SET utf8 ;
USE `creditos` ;

-- -----------------------------------------------------
-- Table `creditos`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `creditos`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(150) NOT NULL,
  `remember_token` VARCHAR(100) NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `creditos`.`clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `creditos`.`clients` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `document` VARCHAR(15) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `fone` VARCHAR(20) NOT NULL,
  `user_id` INT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_clients_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `creditos`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `creditos`.`credits`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `creditos`.`credits` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `value` INT NOT NULL,
  `validity` DATE NOT NULL,
  `description` TEXT NOT NULL,
  `balance` INT NOT NULL,
  `client_id` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_credits_client_idx` (`client_id` ASC),
  CONSTRAINT `fk_credits_client`
    FOREIGN KEY (`client_id`)
    REFERENCES `creditos`.`clients` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `creditos`.`extracts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `creditos`.`extracts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` ENUM('recarga', 'remocao', 'estorno') NOT NULL,
  `description` TEXT NOT NULL,
  `date` TIMESTAMP NOT NULL,
  `credits` INT NOT NULL,
  `operation` ENUM('credito', 'debito') NOT NULL,
  `balance` INT NOT NULL,
  `client_id` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_extracts_client_idx` (`client_id` ASC),
  CONSTRAINT `fk_extracts_client`
    FOREIGN KEY (`client_id`)
    REFERENCES `creditos`.`clients` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
